 SELECT 
 O.ORDERID
 ,O.ORDERDATE
 ,O.SHIPDATE
 ,O.SHIPMODE
 ,O.CUSTOMERID AS CUST
 ,O.PRODUCTID AS PRODID
 ,O.ORDERCOSTPRICE
 ,O.ORDERSELLINGPRICE
 ,C.CUSTOMERID
 ,C.CUSTOMERNAME
 ,C.SEGMENT
 ,C.COUNTRY
 ,C.STATE 
 ,P.CATEGORY
 ,P.PRODUCTID
 ,P.PRODUCTNAME
 ,P.SUBCATEGORY
 ,(O.ORDERSELLINGPRICE-O.ORDERCOSTPRICE) 
AS ORDER_PROFITS
 from 
{{ source('mart','STG_ORDERS') }} AS O
 LEFT JOIN 
{{ ref('stg_products')}} AS P 
ON O.PRODUCTID = P.PRODUCTID
 LEFT JOIN 
{{ source('mart','STG_CUSTOMERS')}} AS C
 ON O.CUSTOMERID = C.CUSTOMERID